FROM rust:1-slim-bookworm AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .
RUN cargo build --release

FROM debian:bookworm-slim AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/target/release/ssm-session /usr/local/bin/
COPY --from=builder /app/target/release/scale-in-ecs /usr/local/bin/
COPY --from=builder /app/target/release/ecr-gitconfig /usr/local/bin/
COPY --from=builder /app/target/release/ses-suppression-list /usr/local/bin/
COPY --from=builder /app/target/release/s3-guardduty-copy /usr/local/bin/
COPY --from=builder /app/target/release/release-codepipelines /usr/local/bin/

CMD ["/bin/bash"]
